/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jg.aquifer;

import org.junit.jupiter.api.Test;

import jg.aquifer.commands.Verifier;
import jg.aquifer.commands.options.VerificationException;

import static org.junit.jupiter.api.Assertions.*;

public class VerifierTest {

    @Test 
    public void testNegWhole() {
        assertThrows(VerificationException.class, 
                     () -> {Verifier.NEG_WHOLE.verify(null, null, "0");}, 
                     "Expected a negative whole number");

        assertThrows(VerificationException.class, 
                     () -> {Verifier.NEG_WHOLE.verify(null, null, "1");}, 
                     "Expected a negative whole number");

        assertThrows(VerificationException.class, 
                     () -> {Verifier.NEG_WHOLE.verify(null, null, "-531.555");}, 
                     "Expected a negative whole number");

        assertThrows(VerificationException.class, 
                     () -> {Verifier.NEG_WHOLE.verify(null, null, "-531.0");}, 
                     "Expected a negative whole number");

        assertDoesNotThrow(() -> {Verifier.NEG_WHOLE.verify(null, null, "-15");}, 
                     "Expected a negative whole number");
    }

    @Test
    public void testNonNegWhole() {
        assertThrows(VerificationException.class, 
                     () -> {Verifier.NON_NEG_WHOLE.verify(null, null, "-95854");}, 
                     "Expected a negative whole number");

        assertThrows(VerificationException.class, 
                     () -> {Verifier.NON_NEG_WHOLE.verify(null, null, "-1");}, 
                     "Expected a negative whole number");

        assertThrows(VerificationException.class, 
                     () -> {Verifier.NON_NEG_WHOLE.verify(null, null, "531.555");}, 
                     "Expected a negative whole number");

        assertThrows(VerificationException.class, 
                     () -> {Verifier.NON_NEG_WHOLE.verify(null, null, "531.0");}, 
                     "Expected a negative whole number");

        assertDoesNotThrow(() -> {Verifier.NON_NEG_WHOLE.verify(null, null, "45");}, 
                     "Expected a negative whole number");

        assertDoesNotThrow(() -> {Verifier.NON_NEG_WHOLE.verify(null, null, "0");}, 
                     "Expected a negative whole number");
    }
}
